### ISSUE TITLE
DB triggers

### ISSUE THREAD

**Issue by karelvasicek** [farmani/yii2-dev-test#4]
Could you please explain their purpose? Are they required?

**Comment by farmani** [comment]
@karelvasicek it grantees that all updates/create will populated. sometime in projects we need to insert/update with query builder or sql command and not using active record in such situations it helps to store with current time when we do not use timestamp behavior

**Comment by karelvasicek** [comment]
Ok, thanks. When using query builder/sql commands `BlammableBehavior` would not be used either, but as for those triggers, this explanation is sufficient. Thanks.
