### ISSUE TITLE
URL rules

### ISSUE THREAD

**Issue by karelvasicek** [farmani/yii2-dev-test#5]
Could you please explain their logic? Are they required?

**Comment by farmani** [comment]
'<controller:(client|contract)>/create' => '<controller>/create',    // this line is not required 
'<controller:(client|contract)>/<id:\d+>/<action:(update|delete)>' => '<controller>/<action>',    // resource/id/update or resource/id/update will redirect to proper equivalent action
'<controller:(client|contract)>/<id:\d+>' => '<controller>/view',    // this line is not required 
'<controller:(client|contract)>s' => '<controller>/index',    // plural resource will redirect to index 
'<controller:\w+>/<id:\d+>'              => '<controller>/view',    // general rules to route for view actions for all possible resources
'<controller:\w+>/<action:\w+>/<id:\d+>' => '<controller>/<action>', // general rules to route for view actions for all possible resources
'<controller:\w+>/<action:\w+>'          => '<controller>/<action>', // general rules to route for view actions for all possible resources



some rules were not required but I put them to show a sample of understanding the way we can use rules in url manager components

**Comment by karelvasicek** [comment]
Ok, thanks.
